using System;
using System.Collections.Generic;
using System.Reflection;
using HarmonyLib;

namespace EverythingCanDieAlternative.ModCompatibility.Handlers
{
    // Compatibility handler for CodeRebirth by XuXiaolan.
    //
    // Most CodeRebirth weapons (CRWeapon melee) call EnemyAI.HitEnemyOnLocalClient and are
    // handled by our standard interception. The Oxidizer (flamethrower) is the exception:
    // its DoHitStuff method calls enemyAI.HitEnemy(...) directly with a non-null player,
    // bypassing HitEnemyOnLocalClient entirely. Our EnemyVsEnemy HitEnemy prefix skips
    // player-attributed hits (to avoid double-processing the vanilla path), so Oxidizer
    // damage vanished into the 999 dummy HP.
    //
    // We patch DoHitStuff with a postfix instead of detecting BURN_HIT_ID in HitEnemy,
    // because the hit ID could be reused by other CodeRebirth sources that go through the
    // proper HitEnemyOnLocalClient path, which would double-process.
    public class CodeRebirthCompatibility : BaseModCompatibility
    {
        public override string ModId => "CodeRebirth";
        public override string ModName => "CodeRebirth";

        // Cached reflection handles for the Oxidizer's private members
        private static FieldInfo _enemyAIListField;

        public override bool IsInstalled
        {
            get
            {
                try
                {
                    // GUID is generated by BepInEx.PluginInfoProps from <AssemblyName>CodeRebirth</AssemblyName>
                    return BepInEx.Bootstrap.Chainloader.PluginInfos.ContainsKey("CodeRebirth");
                }
                catch (Exception ex)
                {
                    Plugin.Log.LogError($"Error detecting {ModName}: {ex.Message}");
                    return false;
                }
            }
        }

        protected override void OnModInitialize()
        {
            try
            {
                PatchOxidizerDoHitStuff();
            }
            catch (Exception ex)
            {
                Plugin.Log.LogError($"Failed to initialize {ModName} compatibility: {ex.Message}");
                Plugin.Log.LogError(ex.StackTrace);
            }
        }

        // ── Patching helpers ─────────────────────────────────────────────────────────

        private void PatchOxidizerDoHitStuff()
        {
            // Resolve the type from CodeRebirth's assembly directly instead of using
            // AccessTools.TypeByName. TypeByName enumerates ALL types in ALL assemblies,
            // which throws a ReflectionTypeLoadException warning for CodeRebirth when its
            // soft dependency OpenBodyCams is not installed. Assembly.GetType(name) only
            // resolves the single requested type and avoids that.
            if (!BepInEx.Bootstrap.Chainloader.PluginInfos.TryGetValue("CodeRebirth", out var pluginInfo) || pluginInfo.Instance == null)
            {
                Plugin.Log.LogWarning($"[{ModName}] Could not resolve CodeRebirth plugin instance — skipping Oxidizer patch");
                return;
            }

            Assembly crAssembly = pluginInfo.Instance.GetType().Assembly;

            // CodeRebirth.src.Content.Items.Oxidizer.DoHitStuff(int damageToDeal)
            Type oxidizerType = crAssembly.GetType("CodeRebirth.src.Content.Items.Oxidizer");
            if (oxidizerType == null)
            {
                Plugin.Log.LogWarning($"[{ModName}] Could not find Oxidizer type — skipping Oxidizer patch");
                return;
            }

            MethodInfo doHitStuffMethod = AccessTools.Method(oxidizerType, "DoHitStuff");
            _enemyAIListField = AccessTools.Field(oxidizerType, "_enemyAIList");

            if (doHitStuffMethod == null || _enemyAIListField == null)
            {
                Plugin.Log.LogWarning($"[{ModName}] Could not find Oxidizer.DoHitStuff or _enemyAIList — skipping Oxidizer patch");
                return;
            }

            Plugin.Harmony.Patch(doHitStuffMethod,
                postfix: new HarmonyMethod(typeof(CodeRebirthCompatibility), nameof(OxidizerDoHitStuffPostfix)));

            Plugin.Log.LogInfo($"[{ModName}] Patched Oxidizer.DoHitStuff");
        }

        // ── Patch implementations ─────────────────────────────────────────────────────

        // Postfix on Oxidizer.DoHitStuff. Positional injection: __0 = damageToDeal.
        // The private _enemyAIList is cleared at the START of DoHitStuff, so after the
        // method it still contains exactly the enemies hit by this call.
        //
        // DoHitStuff runs on EVERY client: the flame tick runs in Update (isBeingUsed is
        // replicated via the vanilla item-activation RPCs) and the exhaust blast runs in
        // a ClientRpc. Only the host processes the damage here — this gives exactly-once
        // semantics and matches our host-authority model. The host's own 0.25s tick
        // cadence produces the same damage rate as the holder's client.
        public static void OxidizerDoHitStuffPostfix(object __instance, int __0)
        {
            try
            {
                if (__0 <= 0) return;
                if (StartOfRound.Instance == null || !StartOfRound.Instance.IsHost) return;

                var holder = (__instance as GrabbableObject)?.playerHeldBy;

                var enemies = _enemyAIListField.GetValue(__instance) as List<EnemyAI>;
                if (enemies == null) return;

                foreach (EnemyAI enemy in enemies)
                {
                    if (enemy == null || enemy.isEnemyDead) continue;

                    Plugin.LogInfo($"[{nameof(CodeRebirthCompatibility)}] Oxidizer hit: {__0} damage to {enemy.enemyType.enemyName}");
                    HealthManager.ProcessHit(enemy, __0, holder);
                }
            }
            catch (Exception ex)
            {
                Plugin.Log.LogError($"[CodeRebirth] OxidizerDoHitStuffPostfix error: {ex.Message}");
            }
        }
    }
}
