name: Mark Stale Branches

on:
  schedule:
    # Run once a day at midnight
    - cron: '0 0 * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 21
          days-before-close: -1  # Don't close branches automatically
          stale-branch-message: 'This branch has been marked as stale because it has not been updated in 21 days'
          stale-branch-label: 'stale'
          only-labels: ''  # Don't restrict to specific labels
          operations-per-run: 100
          delete-branch: false
          include-only-assigned: false
          ascending: false
          remove-stale-when-updated: true
          debug-only: false
          enable-statistics: true
